<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android</TargetFrameworks>
		<RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>

		<OutputType>Exe</OutputType>
		<RootNamespace>TaskManagerUI</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<MauiVersion>9.0.40</MauiVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>TaskManagerUI</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.taskmanagerui</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<EnableSGenConc>True</EnableSGenConc>
		<NoWarn>$(NoWarn);XC0103</NoWarn>
		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DefineConstants>$(DefineConstants)</DefineConstants>
		<EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)' == 'Debug|net9.0-android35.0|AnyCPU'">
		<AndroidLinkMode>None</AndroidLinkMode>
		<RunAOTCompilation>False</RunAOTCompilation>
		<AndroidPackageFormats>apk</AndroidPackageFormats>
		<UseInterpreter>true</UseInterpreter>
		<PublishTrimmed>false</PublishTrimmed>
		<EnableNativeAot>false</EnableNativeAot>
	</PropertyGroup>
	<PropertyGroup>
	<EnableNETAnalyzers>false</EnableNETAnalyzers>
	<AnalysisMode>None</AnalysisMode>
	</PropertyGroup>
	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\Application\Application.csproj" />
		<ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.0" />
		<PackageReference Include="Realm" Version="20.0.0" />
		<PackageReference Include="MediatR" Version="12.2.0" />
		<PackageReference Include="DotNetMeteor.HotReload.Plugin" Version="3.3.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FFImageLoading.Maui" Version="1.2.7" />
		<PackageReference Include="Plugin.LocalNotification" Version="11.1.4" />
		<PackageReference Include="Plugin.Maui.SwipeCardView" Version="1.0.0-preview1" />
		<PackageReference Include="Sharpnado.CollectionView.Maui" Version="3.1.2" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls.Compatibility" Version="2.88.8" />
		<PackageReference Include="CardsView.Maui" Version="1.1.2" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Features\Wellcome\Models\" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Features\Wellcome\Pages\WellcomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>
</Project>